### ISSUE TITLE
Widget cumul apparent sans scroll

### ISSUE THREAD

**Issue by JeanMassiet** [regardscitoyens/direct-parlement#10]
J'ai besoin que le petit écran vert du widget "cumul" soit apparent en permanence à l'écran, sans avoir besoin de scroller vers le bas comme actuellement. 
Pour ça, on pourrait par exemple le placeren bas à droite de l'actuel écran vert des infos députés. 

Il faudrait également faire apparaitre le logo cumul pour les président(e)s et vice-président(e)s de conseils régionaux et départementaux.

Encore mille merci !

**Comment by RouxRC** [comment]
Normalement le cadre du cumul reste toujours figé en haut à droite de la section basse, as-tu bien rafraichi? sinon peux-tu me donner des infos sur ton browser et un screenshot?

**Comment by JeanMassiet** [comment]
Merci Benjamin ça marche impec, je l'ai testé aujourd'hui pendant le pjl
num et ça a beaucoup plus !

2016-05-02 3:45 GMT+02:00 Benjamin Ooghe-Tabanou notifications@github.com:

**Comment by RouxRC** [comment]
une envie de redesign m'a pris, j'ai essayé de réorganiser un peu mieux le layout de tout ça

**Comment by JeanMassiet** [comment]
C'est vraiment super ! Merci Benjamin !
- attention, quand on clique sur "écran vide", tout disparait sauf le logo
  RC. Du coup il flottera tout seul au milieu de l'image :s
- est-il possible (et simple à faire) d'afficher la feuille jaune du Sénat
  comme celle de l'AN ?

Encore merci !

2016-05-03 1:02 GMT+02:00 Benjamin Ooghe-Tabanou notifications@github.com:

**Comment by RouxRC** [comment]
oups corrigé.
Pour la feuille jaune sénat, gérer le dérouleur qui est différent me demandera trop de temps dans l'immédiat

**Comment by JeanMassiet** [comment]
Ah par ailleurs, à l'heure actuelle la largeur du widget des infos députés
dépend de la longueur du nom du Député. Ceux qui ont un nom à rallonge
prennent plus de place à l'écran que ceux qui ont un nom court. Du coup
c'est compliqué à gérer à l'écran et il arrive souvent que ça empiète sur
le graphique d'activité. Serait-il possible de définir une taille type pour
le widget dans laquelle la taille de la police s'adapterait automatiquement
(les noms à rallonge seraient écrits plus petit pour pouvoir rentrer) ?

ça m'aiderait beaucoup à organiser les infos à l'écran.

**Comment by JeanMassiet** [comment]
ok alors ne t'en occupe pas, ce n'est pas du tout urgent !

Le 3 mai 2016 à 09:08, Benjamin Ooghe-Tabanou notifications@github.com a
écrit :

**Comment by RouxRC** [comment]
pour la taille de texte j'ai ajusté normalement pour que ce ne soit pas le cas si tu prends toute la zone dédiée

**Comment by RouxRC** [comment]
ajuster la fonte pour tenir pile poil dans une largeur fixe quel que soit le contenu de texte me semble trop hasardeux pour fonctionner correctement

**Comment by JeanMassiet** [comment]
ok je comprends.
Dans ce cas c'est ok, je prendrai toute la largeur de la zone dédiée.

Le 3 mai 2016 à 09:11, Benjamin Ooghe-Tabanou notifications@github.com a
écrit :

**Comment by JeanMassiet** [comment]
Benjamin j'ai un problème, Direct-Parlement ne fonctionne pas (impossible
de sélectionner un député et la feuille jaune se charge indéfiniement)
Tu peux jeter un oeil avant les QAG ?

**Comment by RouxRC** [comment]
C'est NosDéputés.fr qui ne répondait plus, cela devrait aller mieux

**Comment by JeanMassiet** [comment]
Oui ça marche, merci Benjamin, pardon pour le coup de flip !

By the way, cette aprem je vais commenter la DG de la loi travail...
Jean.

2016-05-03 14:36 GMT+02:00 Benjamin Ooghe-Tabanou notifications@github.com
:
