### ISSUE TITLE
Infos du widget

### ISSUE THREAD

**Issue by RouxRC** [regardscitoyens/direct-parlement#11]
@JeanMassiet Peux-tu me dire s'il y a des choses du widget nosdéputés dont tu ne te sers pas? on peut alléger en virant par exemple le nom titre, la barre de chiffres, etc cf https://www.nosdeputes.fr/widget14?depute=damien-abad

**Comment by JeanMassiet** [comment]
Effectivement ! Je ne me sers ni de la photo, ni du titre, ni de la barre de chiffres !
