### ISSUE TITLE
Icons bug

### ISSUE THREAD

**Issue by JeanMassiet** [regardscitoyens/direct-parlement#12]
There's a bug with "SER" and "Les Republicains" icons : they doesn't work anymore !
cc @RouxRC

**Comment by teymour** [comment]
e17f1ae39510a6492c110733400f191b8b44c8ff corrects the problem
New SER logo has been uploaded (via  c32c0c2e36404ff6a464357902360c6085a078d4 )
Don't forget to clear your cache
